#
SET(CMAKE_SYSTEM_NAME Linux)
SET(CMAKE_SYSTEM_PROCESSOR arm)

SET(CMAKE_C_COMPILER arm-none-eabi-gcc)
SET(CMAKE_CXX_COMPILER arm-none-eabi-gcc)

#SET(CMAKE_C_COMPILER gcc)
#SET(CMAKE_CXX_COMPILER gcc)

